# Generated by Django 5.0.7 on 2024-07-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ing10',
            field=models.BooleanField(blank=True, null=True, verbose_name='huevo'),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='ing11',
            field=models.BooleanField(blank=True, null=True, verbose_name='carne'),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='ing7',
            field=models.BooleanField(blank=True, null=True, verbose_name='papitas'),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='ing8',
            field=models.BooleanField(blank=True, null=True, verbose_name='maiz'),
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='ing9',
            field=models.BooleanField(blank=True, null=True, verbose_name='tocineta'),
        ),
    ]
