# Generated by Django 5.0.7 on 2024-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_hamburguesa_ing10_hamburguesa_ing11_hamburguesa_ing7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='ing10',
            field=models.BooleanField(default=False, verbose_name='huevo'),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='ing11',
            field=models.BooleanField(default=False, verbose_name='carne'),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='ing7',
            field=models.BooleanField(default=False, verbose_name='papitas'),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='ing8',
            field=models.BooleanField(default=False, verbose_name='maiz'),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='ing9',
            field=models.BooleanField(default=False, verbose_name='tocineta'),
        ),
    ]
