# Generated by Django 5.0.7 on 2024-07-19 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_hamburguesa_ing10_alter_hamburguesa_ing11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direction', models.CharField(max_length=50, verbose_name='direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato '+999999999' o '999999999'.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
