# Generated by Django 5.0.7 on 2024-07-19 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato '+999999999' o '999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
