# Generated by Django 5.0.7 on 2024-07-19 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_cliente_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hamburguesa',
            name='user',
        ),
        migrations.AddField(
            model_name='hamburguesa',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persona.cliente'),
            preserve_default=False,
        ),
    ]
