# Generated by Django 5.0.7 on 2024-07-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_remove_hamburguesa_user_hamburguesa_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hamburguesa',
            new_name='Servicio',
        ),
    ]
