# Generated by Django 5.0.7 on 2024-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='Marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
    ]
