# Generated by Django 5.0.7 on 2024-07-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_alter_ingredientes_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='Marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
    ]
