# Generated by Django 5.0.7 on 2024-07-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_alter_ingredientes_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientes',
            old_name='Marca',
            new_name='marca',
        ),
    ]
