# Generated by Django 5.0.7 on 2024-07-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_rename_marca_ingredientes_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
