# Generated by Django 5.0.7 on 2024-07-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0015_servicio_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='ingredientes',
            field=models.ManyToManyField(to='persona.ingredientes'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='status',
            field=models.BooleanField(verbose_name='En el menu'),
        ),
    ]
