# Generated by Django 5.0.7 on 2024-07-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0016_alter_servicio_ingredientes_alter_servicio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='status',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('lista', 'Lista'), ('paga', 'Paga')], default='proceso', max_length=7, verbose_name='Estado'),
        ),
    ]
