# Generated by Django 5.0.7 on 2024-07-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_ingredientes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='status',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('lista', 'Lista'), ('paga', 'Paga'), ('otro', 'Otro')], default='proceso', max_length=7, verbose_name='Estado'),
        ),
    ]
