# Generated by Django 5.0.7 on 2024-07-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0019_payment_type_remove_ingredientes_status_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('lista', 'Lista'), ('paga', 'Paga'), ('otro', 'Otro')], default='proceso', max_length=7, verbose_name='Estado'),
        ),
        migrations.RemoveField(
            model_name='tipopago',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='tipopago',
            name='pedido',
        ),
        migrations.DeleteModel(
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='TipoPago',
        ),
    ]
