# Generated by Django 5.0.7 on 2024-07-19 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0020_alter_pedido_pago_remove_tipopago_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pago',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='name',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('espera', 'Espera'), ('pagado', 'Pagado')], default='pedido', max_length=6, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='TipodePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], default='efectivo', max_length=9, verbose_name='Tipo')),
                ('mount', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.pedido')),
            ],
        ),
    ]
