# Generated by Django 5.0.7 on 2024-07-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0021_remove_pedido_pago_alter_pedido_name_tipodepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodepago',
            name='mount',
            field=models.IntegerField(verbose_name='Monto'),
        ),
    ]
