# Generated by Django 5.0.7 on 2024-07-19 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0022_alter_tipodepago_mount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persona.cliente'),
            preserve_default=False,
        ),
    ]
