# Generated by Django 5.0.7 on 2024-07-19 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0023_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
