# Generated by Django 5.0.7 on 2024-07-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0026_remove_pedido_hora_alter_pedido_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
