# Generated by Django 5.0.7 on 2024-07-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0028_alter_pedido_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
