# Generated by Django 5.0.7 on 2024-07-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0029_alter_pedido_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredientes',
            new_name='Ingrediente',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='ingredientes',
            new_name='Ingrediente',
        ),
    ]
