# Generated by Django 5.0.7 on 2024-07-19 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0030_rename_ingredientes_ingrediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.pedido')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.servicio')),
            ],
        ),
    ]
