# Generated by Django 5.0.7 on 2024-07-19 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0031_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
