# Generated by Django 5.0.7 on 2024-07-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0033_item_cant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='observaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
