# Generated by Django 5.0.7 on 2024-07-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0034_item_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='sss'),
        ),
    ]
