# Generated by Django 5.0.7 on 2024-07-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0035_alter_item_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='observaciones',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
